# -*- coding: utf-8 -*-
"""GlutenFreeRestaurantsWA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgYpZGUIPDVNzCruMH8UmGeAjlcWU-ww
"""

# INSTALLS
!pip install pgeocode

# IMPORTS
from bs4 import BeautifulSoup
import requests
import pgeocode

# FINDING THE ZIPCODES FOR ALL THE DISTRICTS IN WASHINGTON STATE
page_to_scrape = requests.get("https://www.ciclt.net/sn/clt/capitolimpact/gw_ziplist.aspx?FIPS=53033")
soup = BeautifulSoup(page_to_scrape.text, "html.parser")
zip_codes = soup.findAll("a")
districts = set()

for zip_code in zip_codes:
    if zip_code.text.isnumeric():
        # print(zip_code.text)
        districts.add(zip_code.text)

# print(districts)

# ALL RESTAURANT OPTIONS FOR DISTRICTS IN WASHINGTON STATE
districts = list(districts)
restaurants_list = set()

for i in range(len(districts)):
    nomi = pgeocode.Nominatim("US")
    district = districts[i]
    query = nomi.query_postal_code(district)
    lat = query["latitude"]
    lon = query["longitude"]

    page_to_scrape = requests.get(f"https://www.findmeglutenfree.com/search?lat={lat}&lng={lon}&q=&a={districts[i]}&dedicated=t")
    soup = BeautifulSoup(page_to_scrape.text, "html.parser")
    all_restaurants = soup.findAll("a", attrs = "align-middle") # you can also do restaurants_list = set(all_restaurants)
    addresses = soup.findAll("span", attrs = {"class":"sl-addr mt-2"})

    for restaurant, address in zip(all_restaurants, addresses):
        restaurants_list.add(restaurant.text + ": " + address.text)

# RESULT
for restaurant in restaurants_list:
    print(restaurant)